spring:
  application:
    name: user-management
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: hafizfahad447@gmail.com
    password: fahadbutt1103
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


